const projects = [
    
        {
            id:'1',
            name: 'Avocado Store',
            description: 'lorem ipson data',
            image: '/../../../public/project.jpg',
            tags: ['UI/UX','Web Developer'],
            lang: ['JavaScript', 'NextJS', 'React JS','CSS'],
            fram: ['NextJS'],
            tech: ['VSC', 'Github', 'Git'],
            github: 'https://github.com/DannyJacome30/Avocado-Store',
            page: 'https://dannyjacome30.github.io/Avocado-Store/',
            video:'',
            api_use: 'https://platzi-avo.vercel.app/api/avo',
            figma:'',
        },
        {
            id:'2',
            name: 'Portfolio',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['UI/UX','Web Developer'],
            lang:['JavaScript', 'React JS','CSS'],
            fram:['React JS'],
            tech:['VSC', 'Github', 'Git'],
            github: 'https://github.com/DannyJacome30/DannyJacome',
            page: 'https://dannyjacome30.github.io/DannyJacome',
            video:'',
            api_use: '',
            figma: 'https://www.figma.com/file/4TBuy0y544o67w8ZWoTZcr/Portfolio?type=design&node-id=0%3A1&mode=design&t=ryDRDQJok4JzM1kc-1',
        },
        {
            id:'3',
            name: 'Yard Sale',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['UI/UX','Web Developer'],
            lang:['JavaScript', 'React JS','CSS'],
            fram:['React JS'],
            tech:['VSC', 'Github', 'Git'],
            github: '',
            page: '',
            video:'',
            api_use: '',
            figma: 'https://www.figma.com/proto/bcEVujIzJj5PNIWwF9pP2w/Platzi_YardSale?node-id=5-2808&starting-point-node-id=5%3A2808',
        },
        {
            id:'4',
            name: 'To Do',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['UI/UX','Web Developer'],
            lang:['JavaScript', 'React JS','CSS'],
            fram:['React JS'],
            tech:['VSC', 'Github', 'Git'],
            github: 'https://github.com/DannyJacome30/to-do-app',
            page: 'https://dannyjacome30.github.io/to-do-app/',
            video:'',
            api_use: '',
            figma: '',
        },
        {
            id:'5',
            name: 'Nature Web',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['Web','UI/UX'],
            lang:[''],
            fram:[''],
            tech:['Adobe XD'],
            github: '',
            page: '',
            video:'',
            api_use: '',
            figma: '',
        },
        {
            id:'6',
            name: 'Sistema de facturación',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['App Desktop'],
            lang:['Microsof Visual Basic', 'Java','XML'],
            fram:['Microsof Visual Basic'],
            tech:['VSC', 'Github', 'Git','Postman','NetBeans'],
            github: '',
            page: '',
            video:'',
            api_use: '',
            figma: '',
        },
        {
            id:'7',
            name: 'Sistema de gestión movil',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['App Mobile','UI/UX'],
            lang:[''],
            fram:[''],
            tech:['Figma'],
            github: '',
            page: '',
            video:'',
            api_use: '',
            figma: 'https://www.figma.com/proto/BBg1hEPQ676ogQOketqlyO/Prototipo?page-id=0%3A1&type=design&node-id=47-39&viewport=371%2C290%2C0.19&t=Eu7EHwM8g161pKFy-1&scaling=scale-down&starting-point-node-id=47%3A39&show-proto-sidebar=1&mode=design',
        },
        {
            id:'8',
            name: 'Calendar Task',
            description: 'lorem ipson data',
            image: '../../public/Logo_DJ_light.svg',
            tags: ['App Mobile','UI/UX'],
            lang:[''],
            fram:[''],
            tech:['Figma'],
            github: '',
            page: '',
            video:'',
            api_use: '',
            figma: 'https://www.figma.com/file/DfDfvVKRX2dcwzkxzqLljb/Calendar-Task?type=design&node-id=72%3A100&mode=design&t=gohxGJsmeU1L7H0U-1',
        }
]

export default {projects};