const data = [
        [
            {
                id:'1',
                name: 'Avocado Store',
                description: '"Avocado Store" is an e-commerce website that utilizes a public API, to offer a diverse catalog of avocados for purchase. Each avocado listing provides details on its name and price. Users can add avocados to their shopping cart. The site includes a user-friendly navigation menu for easy access to the avocado store and the shopping cart. In the shopping cart section, users can review their selections with quantity and price details. This project demonstrates my ability to create functional and engaging web solutions while leveraging public APIs to enhance the user experience.',
                image: '/projects/avocadoStore.PNG',
                tags: ['UI/UX','Front End Developer'],
                lang: ['JavaScript', 'React JS','CSS'],
                fram: ['NextJS'],
                tech: ['VSC', 'Github', 'Git'],
                github: 'https://github.com/DannyJacome30/Avocado-Store',
                page: 'https://dannyjacome30.github.io/Avocado-Store/',
                video:'',
                api_use: 'https://platzi-avo.vercel.app/api/avo',
                figma:'',
            },
            {
                id:'2',
                name: 'Portfolio',
                description: '"My Portfolio" is a web page designed to showcase my professional accomplishments and provide a comprehensive overview of my work. The portfolio features a collection of projects I have completed, highlights my professional experience, and offers various means of contacting me. Key sections of "My Portfolio" include: \nProjects: A showcase of the projects I have undertaken, complete with descriptions and links to view the projects in detail. \nExperience: An overview of my professional background, including previous roles and responsibilities. \nContact: Contact information and options for getting in touch with me, ensuring seamless communication. \n"My Portfolio" serves as a testament to my skills and achievements, making it easy for potential collaborators and employers to learn more about me and explore my work.',
                image: '/Logo_DJ_light.svg',
                tags: ['UI/UX','Web Developer'],
                lang:['JavaScript', 'React JS','CSS'],
                fram:['Next JS'],
                tech:['VSC', 'Github', 'Git'],
                github: 'https://github.com/DannyJacome30/DannyJacome',
                page: 'https://dannyjacome30.github.io/DannyJacome',
                video:'',
                api_use: '',
                figma: 'https://www.figma.com/file/4TBuy0y544o67w8ZWoTZcr/Portfolio?type=design&node-id=0%3A1&mode=design&t=ryDRDQJok4JzM1kc-1',
            },
            {
                id:'3',
                name: 'Yard Sale',
                description: 'lorem ipson data',
                image: '/projects/yardSale.png',
                tags: ['UI/UX','Web Developer'],
                lang:[''],
                fram:[''],
                tech:['Figma'],
                github: '',
                page: '',
                video:'',
                api_use: '',
                figma: 'https://www.figma.com/proto/bcEVujIzJj5PNIWwF9pP2w/Platzi_YardSale?node-id=5-2808&starting-point-node-id=5%3A2808',
            },
            {
                id:'4',
                name: 'To Do',
                description: 'The "To Do App" is a web page designed to help users manage their tasks and create a list of pending activities. Users can add multiple tasks to the list and easily keep track of completed tasks. The app includes a task completion counter, showing the number of completed tasks out of the total tasks entered. Key features of the "To Do App" include the ability to mark tasks as done, indicating progress, and the option to remove tasks from the list when they are no longer needed. This project showcases my expertise in creating user-friendly and practical web applications that enhance productivity and organization.',
                image: '/projects/toDo.PNG',
                tags: ['UI/UX','Web Developer'],
                lang:['JavaScript', 'React JS','CSS'],
                fram:['React JS'],
                tech:['VSC', 'Github', 'Git'],
                github: 'https://github.com/DannyJacome30/to-do-app',
                page: 'https://dannyjacome30.github.io/to-do-app/',
                video:'',
                api_use: '',
                figma: '',
            },
            {
                id:'5',
                name: 'Nature Web',
                description: 'lorem ipson data',
                image: '/Logo_DJ_light.svg',
                tags: ['Web','UI/UX'],
                lang:[''],
                fram:[''],
                tech:['Adobe XD'],
                github: '',
                page: '',
                video:'',
                api_use: '',
                figma: '',
            },
            {
                id:'6',
                name: 'Sistema de gestión y facturación',
                description: 'This project focuses on the creation of a small business management system designed specifically for small businesses, offering a comprehensive solution that covers everything from customer management to inventory control and the generation of essential documents such as purchase orders, quotations, and delivery notes. This system also provides detailed tracking of payments to suppliers and accounts receivable, particularly useful for businesses that handle checks. Furthermore, it complies with the regulations of the Sistema de Rentas Internas (SRI) by connecting to their system for invoice authorization and allows for the sending of invoices via email to customers. In summary, this system optimizes the management of small businesses and enhances their operational efficiency. This project is currently operational in the company "MC Ingeniería Mecánica".',
                
                image: '/Logo_DJ_light.svg',
                tags: ['App Desktop'],
                lang:['Microsof Visual Basic', 'Java','XML'],
                fram:['Microsof Visual Basic'],
                tech:['VSC', 'Github', 'Git','Postman','NetBeans'],
                github: '',
                page: '',
                video:'',
                api_use: '',
                figma: '',
            },
            {
                id:'7',
                name: 'Sistema de gestión movil',
                description: 'This project focuses on the design of a custom order management system, developed to meet the specific needs of a small company, based on requirements provided by its manager. The system allows for the input of order notes, which are stored in a list with filtering and sorting options. Each order is accompanied by a status that can be marked as "urgent," and there is a verification function to mark orders as "delivered." Additionally, the system includes a login system that enables users to access their profiles, which contain personal information and data regarding their role within the company. In summary, this solution is specifically designed to enhance efficiency in order management for the company, ensuring greater organization and adaptability to business needs.',
                image: '/projects/sistemaGestionMovil.PNG',
                tags: ['App Mobile','UI/UX'],
                lang:[''],
                fram:[''],
                tech:['Figma'],
                github: '',
                page: '',
                video:'',
                api_use: '',
                figma: 'https://www.figma.com/proto/BBg1hEPQ676ogQOketqlyO/Prototipo?page-id=0%3A1&type=design&node-id=47-39&viewport=371%2C290%2C0.19&t=Eu7EHwM8g161pKFy-1&scaling=scale-down&starting-point-node-id=47%3A39&show-proto-sidebar=1&mode=design',
            },
            {
                id:'8',
                name: 'Calendar Task',
                description: 'lorem ipson data',
                image: '/projects/calendarTask.PNG',
                tags: ['App Mobile','UI/UX'],
                lang:[''],
                fram:[''],
                tech:['Figma'],
                github: '',
                page: '',
                video:'',
                api_use: '',
                figma: 'https://www.figma.com/file/DfDfvVKRX2dcwzkxzqLljb/Calendar-Task?type=design&node-id=72%3A100&mode=design&t=gohxGJsmeU1L7H0U-1',
            }
        ],
        [
            {
                id:'a',
                name:'Autoridad, dirección y liderazgo',
                ent:'Universidad Nacional Autónoma de México',
                certificado:'https://www.coursera.org/account/accomplishments/verify/WN3KYMU487VX',
                fecha:'28/09/2020',
                horas: '8',
                habilidades: 'Delegation, leadership, coaching, supervision',
                tags: [],   
            },
            {
                id:'f',
                name:'Gestión efectiva del tiempo',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1sMIApyIDJP8a28W1MyAe6hoVtdodFA_v/view?usp=sharing',
                fecha:'11/03/2022',
                horas: '12',
                habilidades: 'Planning, Project Planning',
                tags: [],
            },
            {
                id:'b',
                name:'Iniciación y planificación de proyectos',
                ent:'Tecnológico de Monterrey',
                certificado:'https://www.coursera.org/account/accomplishments/verify/FLU37MTQNWPS',
                fecha:'07/11/2020',
                horas: '5',
                habilidades: 'Project Management, Leadership, Planning, Project Planning',
                tags: [],
            },
            {
                id:'q',
                name:'Trabajo en equipo',
                ent:'Conquito',
                certificado:' https://drive.google.com/file/d/1KTwhHqvaaaFP6kncXznbZNHPyL2zFesG/view?usp=sharing',
                fecha:'16/04/2021',
                horas: '8',
                habilidades: 'Teamwork',
                tags: [],
            },
            {
                id:'h',
                name:'Scrum Foundation Professional Certificate SPFC',
                ent:'CertiProf',
                certificado:'https://drive.google.com/file/d/1NKps2cJUX9LUiUCw3Vo4-ppz2gXjIEgm/view?usp=sharing',
                fecha:'28/05/2022',
                horas: '8',
                habilidades: 'SCRUM',
                tags: [],
            },
            {
                id:'k',
                name:'Curso Profesional de Git y Github',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1irU32jicet5lzXbVVkh6MWf-wg_obrmv/view?usp=sharing',
                fecha:'03/10/2022',
                horas: '22',
                habilidades: 'Git, GitHub',
                tags: [],
            },
            {
                id:'j',
                name:'Transformación Digital',
                ent:'Instituto Europeo de Posgrado IEP',
                certificado:'https://drive.google.com/file/d/1IKnNqdgQ6g79KWhEt9XGOBHuKTJGX9cG/view?usp=sharing',
                fecha:'26/06/2022',
                horas: '50',
                habilidades: 'Digital Transformation',
                tags: [],
            },
            
            {
                id:'i',
                name:'Curso básico de Python',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1Z7neW3nLkgKzGpCN-FoD3f8XrGrXhYwP/view?usp=sharing',
                fecha:'05/05/2022',
                horas: '16',
                habilidades: 'Python',
                tags: [],
            },
            {
                id:'r',
                name:'Python Data Structures',
                ent:'University of Michigan',
                certificado:'https://www.coursera.org/account/accomplishments/verify/C9Z6C3VGFC5C',
                fecha:'01/10/2020',
                horas: '19',
                habilidades: 'Phyton Syntax and Semantics, Data Structure, Python programming, Pythony',
                tags: [],
            },
            {
                id:'d',
                name:'Using databases with Python',
                ent:'University of Michigan',
                certificado:'https://www.coursera.org/account/accomplishments/verify/H5VK3E3A288T',
                fecha:'10/11/2020',
                horas: '14',
                habilidades: 'Phyton Programming, Database (DBMS), SQL',
                tags: [],
            },
            {
                id:'c',
                name:'Capstone: retrieving, processing and visualizing data with Python',
                ent:'University of Michigan',
                certificado:'https://www.coursera.org/account/accomplishments/verify/7A2Q3BGZ5MHZ',
                fecha:'10/11/2020',
                horas: '9',
                habilidades: 'Data Analysys, Phyton Programming, Database (DBMS), Data visualization',
                tags: [],
            },
            {
                id:'e',
                name:'Análisis de negocios para ciencia de datos',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1UM7A2vMfsbmrrKAhTcQL8VG8aVmVsSOM/view?usp=sharing',
                fecha:'11/03/2022',
                horas: '10',
                habilidades: 'Data Science, Business Intelligence',
                tags: [],
            },
            {
                id:'g',
                name:'Data Science e Inteligencia Artificial',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/11-GY0fiq0bWd04XJDzHZ4BH4DNZ-H7JZ/view?usp=sharing',
                fecha:'25/04/2022',
                horas: '14',
                habilidades: 'Data Science, Intelligence Artifitial',
                tags: [],
            },
            {
                id:'l',
                name:'Curso Frontend Developer',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1D-ixByX_jOD7mcLvnBPxNwB1jLKAM3Al/view?usp=sharing',
                fecha:'04/10/2022',
                horas: '15',
                habilidades: 'Frontend',
                tags: [],
            },
            {
                id:'m',
                name:'Curso práctico de Frontend Developer',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1zn288Hq9O_K0i86TcobVOoMGeYSCgNGU/view?usp=sharing',
                fecha:'17/01/2023',
                horas: '13',
                habilidades: 'Frontend',
                tags: [],
            },
            {
                id:'n',
                name:'Curso de Javascript',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1vV8QIk1nbMTPzqZRwl285ANork52GDiF/view?usp=sharing',
                fecha:'17/01/2023',
                horas: '19',
                habilidades: 'Javascript',
                tags: [],
            },
            {
                id:'o',
                name:'Closures y scope en JavaScript',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1Nyyt10wZhLbXLQ0J2TT_DQ6RYgsTANYV/view?usp=sharing',
                fecha:'31/01/2023',
                horas: '13',
                habilidades: 'Javascript',
                tags: [],
            },
            {
                id:'p',
                name:'Asincronismo con JavaScript',
                ent:'Platzi',
                certificado:'https://drive.google.com/file/d/1KWg_TxB4qf6O28swdPYSQ327-5VAVROk/view?usp=sharing',
                fecha:'07/02/2023',
                horas: '18',
                habilidades: 'Javascript',
                tags: [],
            },
            
            

        ]
        [
            {
                id:'w1',
                position:'internship',
                name_company:'Laboratorio de sistemas de informacion e inclusión digital - LUDOLAB',
                page:'https://fis.epn.edu.ec/index.php/es/la-facultad/departamento-de-informatica-y-ciencias-de-la-computacion/laboratorios-de-investigacion/169-laboratorio-de-experimentacion-en-el-diseno-de-sistemas-de-informacion-sociales',
                activities:'',
            }
        ]
        
]   

export default {data};